### ISSUE TITLE
Symbol's function definition is void: shr-render-region

### ISSUE THREAD

**Issue by Lenbok** [emacs-pe/gh-md.el#3]
I just installed this from melpa and when I try it out I get:

error in process filter: Symbol's function definition is void: shr-render-region

I am using emacs 24.3.1. Has the elpa install missed pulling in a dependency?

**Comment by PuercoPop** [comment]
That's weird, shr.el comes with emacs since 24.3.1 AFAIK, Could you try explicitly requiring shr before trying to use gh-md? ( executing (require 'shr) in the _scratch_ buffer)?

Also could you check if you have shr.el anywhere in your emacs path? The way I would check it is C-h f shr-<tab> to open the help of any function and they following the link to the file it is defined in.

**Comment by Lenbok** [comment]
C-h f on shr-render-buffer (after requiring it explicitly from _scratch_) just says

shr-render-buffer is an interactive compiled Lisp function.

without listing a file. 

Running locate shr.el returns: /usr/share/emacs/24.3/lisp/gnus/shr.elc

**Comment by ChillarAnand** [comment]
@PuercoPop  @Lenbok  any updates on this? i am also stuck at same error

**Comment by ChillarAnand** [comment]
@marsam  Thanks
